[build]
  command = ""
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"

    
[[redirects]]
  from = "/admin/part1.html"
  to = "/unauthorized"
  status = 200
  condition = { Role = "!viewer" }
